name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Dependencies with Yarn
        run: yarn install

      - name: Build your project with Yarn
        run: yarn build # 프로젝트에 따라 빌드 스크립트가 다를 수 있습니다.

      - name: Copy build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./dist/*" # 빌드된 파일들의 위치, 필요에 따라 변경해주세요.
          target: "~/your-target-directory" # 원하는 대상 디렉토리
          strip_components: 1

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 3000
          script_stop: true
          script: |
             # 기존 Node.js 프로세스 종료
             pm2 stop all || true
             # 프로젝트 디렉토리로 이동
             cd ~/your-target-directory
             # 디펜던시 설치
             yarn install --production
             # 애플리케이션 시작 (pm2 사용)
             pm2 start index.js --name your-app-name
             # pm2 프로세스 리스트 확인
             pm2 list
