name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Dependencies with Yarn
        run: yarn install

      - name: Build your project with Yarn
        run: yarn build # 이제 이 부분은 build-script.js를 실행합니다.

      - name: Copy build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22 # SSH 포트를 올바르게 설정하세요.
          source: "./dist/*" # build-script.js가 파일을 여기에 생성한다고 가정합니다.
          target: "~/your-target-directory" # 실제 배포 대상 경로로 변경해야 합니다.
          strip_components: 1

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22 # SCP와 동일한 포트를 사용합니다.
          script_stop: true
          script: |
             # 기존 Node.js 프로세스 종료
             pm2 stop all || true
             # 프로젝트 디렉토리로 이동, 실제 경로로 변경해야 합니다.
             cd ~/your-target-directory
             # 디펜던시 설치
             yarn install --production
             # 애플리케이션 시작 (pm2 사용), 애플리케이션 실제 이름으로 변경
             pm2 start your-start-script.js --name your-app-name
             # pm2 프로세스 리스트 확인
             pm2 list
