name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Dependencies with Yarn
        run: yarn install

      # Removed the "Build your project with Yarn" step here
 
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./" # Copying everything from the root. Change this if needed.
          target: "~/gittest"
          strip_components: 1

      - name: SSH Commands 
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            # Create ~/.npm-global directory if it doesn't exist
            mkdir -p ~/.npm-global
            # Set npm prefix to user's home directory
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            
            # Install pm2 if not installed
            npm list -g pm2 || npm install pm2 -g
            # Install Yarn if not installed
            npm list -g yarn || npm install yarn -g

            # Stop the existing Node.js process
            pm2 stop all || true
            # Move to the project directory
            cd ~/your-app-directory
            # Install dependencies
            yarn install --production
            # Start the application using pm2
            pm2 start app.js --name your-app-name
            # Check the pm2 process list
            pm2 list